### ISSUE TITLE
feature: add ability to specify a webhook which gets called after every successful page scrape

### ISSUE THREAD

**Issue by skeptrunedev** [devflowinc/firecrawl-simple#22]
Webhook should most likely get called by the `scrape` hero service in apps and not the primary firecrawl server.

**Comment by vtempest** [comment]
https://qwksearch.com/docs/api/extract-from-any-url-the-main-content-and-cite

Firecrawl Simple will get blocked on 40% of sites that use anti-scraper tech.. I have checkers for bot detection, 4 backup methods if initial fetch is blocked.

How do you deal with that 20% of sites will IP block your datacenters? It needs to run on clientside using client's IP

Let me know when you want to talk and integrate the QwkSearch API -- which uses the best trifaliature algorithms to extract content and APA academic cite -- better than perplexity since this gives full content

This is a great integration and you should be willing to add such tools to your stack. The pricing is very reasonable considering you;re attempting to charge businesses 5k/month for reselling open source software :) 

@skeptrune Nick Khami you should stop this passive aggressive telling everyone to ignore me and looking to exclude because you cannot deal with altenative ideas. This goes against your own conduct policy to have a welcoming environment and will only get worse next 20y with ai agents and investors will know. You used to call yc founders elitist assholes... then you became one... hopefully you can put behind your petty passive aggressive looking for excuses to exclude and integrate my services :)

**Comment by skeptrunedev** [comment]
Completed
